version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
