services:
  api:
    build: .
    image: mozaik-heartbeat
    container_name: mozaik-api
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: mozaik-db
    environment:
      POSTGRES_USER: mozaik
      POSTGRES_PASSWORD: mozaik
      POSTGRES_DB: mozaik
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: mozaik-adminer
    ports:
      - "8080:8080"

volumes:
  pgdata:
